language: rust
rust:
    - stable
    - nightly

script:
    - cargo build
    - cargo test
    - cargo build --features=redis-backend
    - cargo test --features=redis-backend

cache:
    directories:
        - $HOME/.cargo
        - target
        - local
